### ISSUE TITLE
Question: differences to previous NDI plugin

### ISSUE THREAD

**Issue by hybridherbst** [keijiro/NDIUnityInteropTest#1]
Hey there, great that you're picking NDI up again!
Mind elaborating a bit what the differences/pros/cons of this version vs. the previous one are?

Is there a chance that this new one will get better Android/iOS support or metadata? 😄

Keep up the great work, and thanks a lot!

**Comment by keijiro** [comment]
The goal of this repository is to replace the C++ native plugin implementation with C# interop. I've almost achieved that goal -- This repository doesn't contain any C++ code.

The good point about C# interop is that you can easily extend the plugin without hassling with C++. You can add metadata support if you need it.

Please don't expect better mobile support at the moment. The official SDK still only supports sender functionality on mobiles.
